### ISSUE TITLE
Grammatical errors

### ISSUE THREAD

**Issue by jack9603301** [any1/aml#11]
Grammatical errors

![图片](https://user-images.githubusercontent.com/9047180/209126228-b59d3388-2eef-40c3-b09f-21a39ba9e9f9.png)

**Comment by chewi** [comment]
It looks like you're a Gentoo user.

This fails because Gentoo tried to fix the build on musl by removing sys/queue.h in favour of the system-wide version. The bundled queue.h doesn't work on musl because it depends on sys/cdefs.h, which musl doesn't have. However, it also includes `LIST_FOREACH_SAFE`, which neither glibc nor musl have. It looks like this header came from FreeBSD? If you're going to use additional macros, please put them in a separate header. I have effectively done this for Gentoo with success, although I haven't tested with musl yet.

**Comment by jack9603301** [comment]
@chewi Can you tell me the specific operation or example?

**Comment by chewi** [comment]
Sorry, I was not clear. I have patched a fix into Gentoo, so you should not have any further trouble. The other information was for @any1.

**Comment by chewi** [comment]
Thanks! That should do the trick.

**Comment by jack9603301** [comment]
This is a closed issue, I will close it

**Comment by jack9603301** [comment]
This is a closed issue, I will close it
